[package]
name = "bitpack-vec"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divrem = "1.0.0"
deepsize = "0.2.0"
serde = { version = "1.0", features = ["derive"] }